/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as TopRouteImport } from './routes/top'
import { Route as SeguidosRouteImport } from './routes/seguidos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecomendacionesRouteImport } from './routes/recomendaciones'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as ArtistasIdRouteImport } from './routes/artistas.$id'
import { Route as AlbumesIdRouteImport } from './routes/albumes.$id'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguidosRoute = SeguidosRouteImport.update({
  id: '/seguidos',
  path: '/seguidos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendacionesRoute = RecomendacionesRouteImport.update({
  id: '/recomendaciones',
  path: '/recomendaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasIdRoute = ArtistasIdRouteImport.update({
  id: '/artistas/$id',
  path: '/artistas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumesIdRoute = AlbumesIdRouteImport.update({
  id: '/albumes/$id',
  path: '/albumes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/registro': typeof RegistroRoute
  '/seguidos': typeof SeguidosRoute
  '/top': typeof TopRoute
  '/wrapped': typeof WrappedRoute
  '/albumes/$id': typeof AlbumesIdRoute
  '/artistas/$id': typeof ArtistasIdRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/registro': typeof RegistroRoute
  '/seguidos': typeof SeguidosRoute
  '/top': typeof TopRoute
  '/wrapped': typeof WrappedRoute
  '/albumes/$id': typeof AlbumesIdRoute
  '/artistas/$id': typeof ArtistasIdRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists': typeof PlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/registro': typeof RegistroRoute
  '/seguidos': typeof SeguidosRoute
  '/top': typeof TopRoute
  '/wrapped': typeof WrappedRoute
  '/albumes/$id': typeof AlbumesIdRoute
  '/artistas/$id': typeof ArtistasIdRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/favoritos'
    | '/recomendaciones'
    | '/registro'
    | '/seguidos'
    | '/top'
    | '/wrapped'
    | '/albumes/$id'
    | '/artistas/$id'
    | '/playlists/$id'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/buscar'
    | '/favoritos'
    | '/recomendaciones'
    | '/registro'
    | '/seguidos'
    | '/top'
    | '/wrapped'
    | '/albumes/$id'
    | '/artistas/$id'
    | '/playlists/$id'
    | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/favoritos'
    | '/recomendaciones'
    | '/registro'
    | '/seguidos'
    | '/top'
    | '/wrapped'
    | '/albumes/$id'
    | '/artistas/$id'
    | '/playlists/$id'
    | '/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuscarRoute: typeof BuscarRoute
  FavoritosRoute: typeof FavoritosRoute
  RecomendacionesRoute: typeof RecomendacionesRoute
  RegistroRoute: typeof RegistroRoute
  SeguidosRoute: typeof SeguidosRoute
  TopRoute: typeof TopRoute
  WrappedRoute: typeof WrappedRoute
  AlbumesIdRoute: typeof AlbumesIdRoute
  ArtistasIdRoute: typeof ArtistasIdRoute
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguidos': {
      id: '/seguidos'
      path: '/seguidos'
      fullPath: '/seguidos'
      preLoaderRoute: typeof SeguidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendaciones': {
      id: '/recomendaciones'
      path: '/recomendaciones'
      fullPath: '/recomendaciones'
      preLoaderRoute: typeof RecomendacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/$id': {
      id: '/artistas/$id'
      path: '/artistas/$id'
      fullPath: '/artistas/$id'
      preLoaderRoute: typeof ArtistasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albumes/$id': {
      id: '/albumes/$id'
      path: '/albumes/$id'
      fullPath: '/albumes/$id'
      preLoaderRoute: typeof AlbumesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuscarRoute: BuscarRoute,
  FavoritosRoute: FavoritosRoute,
  RecomendacionesRoute: RecomendacionesRoute,
  RegistroRoute: RegistroRoute,
  SeguidosRoute: SeguidosRoute,
  TopRoute: TopRoute,
  WrappedRoute: WrappedRoute,
  AlbumesIdRoute: AlbumesIdRoute,
  ArtistasIdRoute: ArtistasIdRoute,
  PlaylistsIdRoute: PlaylistsIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
